import express, { Request, Response } from 'express';
import cors from 'cors';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import multer from 'multer';
import { getDb, saveDb } from './db.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 5000;

// Uploads directory
const UPLOADS_DIR = path.join(__dirname, 'uploads');
if (!fs.existsSync(UPLOADS_DIR)) {
  fs.mkdirSync(UPLOADS_DIR, { recursive: true });
}

// Multer storage
const storage = multer.diskStorage({
  destination: (_req, _file, cb) => {
    cb(null, UPLOADS_DIR);
  },
  filename: (_req, file, cb) => {
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1e9);
    cb(null, uniqueSuffix + '-' + file.originalname.replace(/[^a-zA-Z0-9.-]/g, '_'));
  },
});
const upload = multer({ storage });

// Middleware
app.use(cors());
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true, limit: '50mb' }));
app.use('/uploads', express.static(UPLOADS_DIR));

// Logging middleware
app.use((req, _res, next) => {
  console.log(`[SONVÉRA API] ${req.method} ${req.url}`);
  next();
});

// Helper for DDEX XML generation
function generateDdexXml(release: any): string {
  const timestamp = new Date().toISOString();
  const messageId = `ERN43_SONVERA_${release.upc || 'UPC'}_${Date.now()}`;

  return `<?xml version="1.0" encoding="UTF-8"?>
<ern:NewReleaseMessage xmlns:ern="http://ddex.net/xml/ern/43" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" MessageSchemaVersionId="ern/43" LanguageAndScriptCode="en">
  <MessageHeader>
    <MessageThreadId>${messageId}</MessageThreadId>
    <MessageId>${messageId}</MessageId>
    <MessageSender>
      <PartyId Namespace="PADPIDA">PADPIDA2026SONVERA01</PartyId>
      <PartyName>
        <FullName>SONVÉRA Global Music Distribution Platform (Sandbox)</FullName>
      </PartyName>
    </MessageSender>
    <MessageRecipient>
      <PartyId Namespace="PADPIDA">DSP_AGGREGATOR_INSPECTOR</PartyId>
      <PartyName>
        <FullName>Global DSP Partner Gateway</FullName>
      </PartyName>
    </MessageRecipient>
    <MessageCreatedDateTime>${timestamp}</MessageCreatedDateTime>
    <Comment>Automated DDEX ERN 4.3 export generated by SONVÉRA backend</Comment>
  </MessageHeader>

  <PartyList>
    <Party>
      <PartyReference>P_ARTIST_1</PartyReference>
      <PartyName>
        <FullName>${release.primaryArtist || 'Unknown Artist'}</FullName>
      </PartyName>
    </Party>
    <Party>
      <PartyReference>P_LABEL_1</PartyReference>
      <PartyName>
        <FullName>${release.labelName || 'Independent'}</FullName>
      </PartyName>
    </Party>
  </PartyList>

  <ResourceList>
${(release.tracks || [])
  .map(
    (t: any, idx: number) => `    <SoundRecording>
      <ResourceReference>A_${idx + 1}</ResourceReference>
      <Type>MusicalWorkSoundRecording</Type>
      <SoundRecordingId>
        <ISRC>${t.isrc || 'PENDING'}</ISRC>
      </SoundRecordingId>
      <DisplayTitleText>${t.title}</DisplayTitleText>
      <DisplayArtistName>${t.primaryArtist || release.primaryArtist}</DisplayArtistName>
      <Duration>PT${Math.floor((t.audioSpec?.durationSeconds || 180) / 60)}M${(t.audioSpec?.durationSeconds || 180) % 60}S</Duration>
      <SoundRecordingDetailsByTerritory>
        <TerritoryCode>Worldwide</TerritoryCode>
        <Title TitleType="FormalTitle">
          <TitleText>${t.title}</TitleText>
        </Title>
        <DisplayArtist>
          <PartyReference>P_ARTIST_1</PartyReference>
          <ArtistRole>MainArtist</ArtistRole>
        </DisplayArtist>
        <PLine>
          <Year>${release.pLineYear || 2026}</Year>
          <PLineCompany>${release.pLineOwner || release.primaryArtist}</PLineCompany>
        </PLine>
        <Genre>
          <GenreText>${release.primaryGenre || 'Electronic'}</GenreText>
        </Genre>
        <ParentalWarningType>${t.isExplicit ? 'Explicit' : 'NotExplicit'}</ParentalWarningType>
      </SoundRecordingDetailsByTerritory>
    </SoundRecording>`
  )
  .join('\n')}
    <Image>
      <ResourceReference>IMG_FRONT_COVER</ResourceReference>
      <Type>FrontCoverImage</Type>
      <ImageDetailsByTerritory>
        <TerritoryCode>Worldwide</TerritoryCode>
        <TechnicalDetails>
          <TechnicalResourceDetailsReference>T_IMG</TechnicalResourceDetailsReference>
          <ImageCodecType>${release.artwork?.format || 'JPEG'}</ImageCodecType>
          <ImageHeight>${release.artwork?.height || 3000}</ImageHeight>
          <ImageWidth>${release.artwork?.width || 3000}</ImageWidth>
        </TechnicalDetails>
      </ImageDetailsByTerritory>
    </Image>
  </ResourceList>

  <ReleaseList>
    <Release>
      <ReleaseReference>R_MAIN</ReleaseReference>
      <ReleaseId>
        <ICPN>${release.upc || 'NOUPC'}</ICPN>
        <CatalogNumber>${release.catalogNumber || 'SVR-001'}</CatalogNumber>
      </ReleaseId>
      <ReferenceTitle>
        <TitleText>${release.title}</TitleText>
      </ReferenceTitle>
      <ReleaseType>${(release.releaseType || 'single').toUpperCase()}</ReleaseType>
      <ReleaseDetailsByTerritory>
        <TerritoryCode>Worldwide</TerritoryCode>
        <DisplayArtistName>${release.primaryArtist}</DisplayArtistName>
        <LabelName>${release.labelName || 'Independent'}</LabelName>
        <CLine>
          <Year>${release.cLineYear || 2026}</Year>
          <CLineCompany>${release.cLineOwner || release.primaryArtist}</CLineCompany>
        </CLine>
        <OriginalReleaseDate>${release.releaseDate || '2026-10-18'}</OriginalReleaseDate>
      </ReleaseDetailsByTerritory>
    </Release>
  </ReleaseList>
</ern:NewReleaseMessage>`;
}

// -------------------------------------------------------------
// ENDPOINTS
// -------------------------------------------------------------

// 1. Health check
app.get('/api/health', (_req: Request, res: Response) => {
  res.json({
    status: 'online',
    platform: 'SONVÉRA Global Music Distribution Engine',
    version: '2026.4.1-ERN4.3',
    provider: 'SonveraDemoProvider',
    isSandbox: true,
    timestamp: new Date().toISOString(),
  });
});

// 2. Get all releases
app.get('/api/releases', (req: Request, res: Response) => {
  const db = getDb();
  let results = [...db.releases];

  const { status, type, q } = req.query;

  if (status && status !== 'ALL') {
    results = results.filter((r) => r.status === status);
  }
  if (type && type !== 'ALL') {
    results = results.filter((r) => r.releaseType === type);
  }
  if (q && typeof q === 'string') {
    const term = q.toLowerCase();
    results = results.filter(
      (r) =>
        r.title?.toLowerCase().includes(term) ||
        r.primaryArtist?.toLowerCase().includes(term) ||
        r.upc?.includes(term)
    );
  }

  res.json({ success: true, count: results.length, data: results });
});

// 3. Get single release by ID
app.get('/api/releases/:id', (req: Request, res: Response) => {
  const db = getDb();
  const release = db.releases.find((r) => r.id === req.params.id);
  if (!release) {
    return res.status(404).json({ success: false, error: 'Release not found' });
  }
  res.json({ success: true, data: release });
});

// 4. Create new release
app.post('/api/releases', (req: Request, res: Response) => {
  const db = getDb();
  const newRelease = {
    ...req.body,
    id: req.body.id || `rel-${Date.now()}`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: req.body.status || 'DRAFT',
    statusHistory: req.body.statusHistory || [
      {
        id: `sh-${Date.now()}`,
        status: 'DRAFT',
        timestamp: new Date().toISOString(),
        note: 'Release created in Release Center.',
        actor: req.body.primaryArtist || 'Artist',
      },
    ],
  };

  db.releases.unshift(newRelease);
  saveDb(db);

  res.status(201).json({ success: true, data: newRelease });
});

// 5. Update existing release
app.put('/api/releases/:id', (req: Request, res: Response) => {
  const db = getDb();
  const index = db.releases.findIndex((r) => r.id === req.params.id);

  if (index === -1) {
    return res.status(404).json({ success: false, error: 'Release not found' });
  }

  const updated = {
    ...db.releases[index],
    ...req.body,
    updatedAt: new Date().toISOString(),
  };

  db.releases[index] = updated;
  saveDb(db);

  res.json({ success: true, data: updated });
});

// 6. Submit release for distribution
app.post('/api/releases/:id/submit', (req: Request, res: Response) => {
  const db = getDb();
  const index = db.releases.findIndex((r) => r.id === req.params.id);

  if (index === -1) {
    return res.status(404).json({ success: false, error: 'Release not found' });
  }

  const targetDsps = req.body.dsps || db.releases[index].selectedDsps || [
    'spotify',
    'apple_music',
    'youtube_music',
    'amazon_music',
  ];

  const batchId = `BATCH-${Date.now().toString(36).toUpperCase()}-${Math.floor(1000 + Math.random() * 9000)}`;

  const updated = {
    ...db.releases[index],
    status: 'PROCESSING',
    submittedAt: new Date().toISOString(),
    statusHistory: [
      ...(db.releases[index].statusHistory || []),
      {
        id: `sh-sub-${Date.now()}`,
        status: 'SUBMITTED',
        timestamp: new Date().toISOString(),
        note: `Submitted for DDEX ERN 4.3 distribution to ${targetDsps.length} DSPs. Batch: ${batchId}`,
        actor: db.releases[index].primaryArtist,
        batchId,
      },
      {
        id: `sh-proc-${Date.now()}`,
        status: 'PROCESSING',
        timestamp: new Date().toISOString(),
        note: 'Ingestion pipeline converting DDEX feeds and packaging WAV audio packages.',
        actor: 'SONVÉRA Sandbox Hub',
      },
    ],
    deliveryStatuses: targetDsps.map((dspId: string) => ({
      dspId,
      dspName: dspId.replace('_', ' ').toUpperCase(),
      status: 'INGESTING',
      deliveryBatchId: batchId,
      deliveredAt: new Date().toISOString(),
    })),
    updatedAt: new Date().toISOString(),
  };

  db.releases[index] = updated;
  saveDb(db);

  res.json({
    success: true,
    batchId,
    status: 'PROCESSING',
    message: `Release successfully dispatched to ${targetDsps.length} partner streaming networks.`,
    data: updated,
  });
});

// 7. Request Takedown
app.post('/api/releases/:id/takedown', (req: Request, res: Response) => {
  const db = getDb();
  const index = db.releases.findIndex((r) => r.id === req.params.id);

  if (index === -1) {
    return res.status(404).json({ success: false, error: 'Release not found' });
  }

  const updated = {
    ...db.releases[index],
    status: 'TAKEDOWN_REQUESTED',
    statusHistory: [
      ...(db.releases[index].statusHistory || []),
      {
        id: `sh-td-${Date.now()}`,
        status: 'TAKEDOWN_REQUESTED',
        timestamp: new Date().toISOString(),
        note: `Takedown notice broadcast to all connected DSP stores. Reason: ${req.body.reason || 'Artist requested'}`,
        actor: req.body.actor || 'Artist',
      },
    ],
    updatedAt: new Date().toISOString(),
  };

  db.releases[index] = updated;
  saveDb(db);

  res.json({ success: true, message: 'Takedown notice successfully broadcast.', data: updated });
});

// 8. Download / Inspect DDEX XML
app.get('/api/releases/:id/ddex', (req: Request, res: Response) => {
  const db = getDb();
  const release = db.releases.find((r) => r.id === req.params.id);

  if (!release) {
    return res.status(404).json({ success: false, error: 'Release not found' });
  }

  const xml = generateDdexXml(release);
  res.setHeader('Content-Type', 'application/xml');
  res.send(xml);
});

// 9. File upload: Audio
app.post('/api/upload/audio', upload.single('audio'), (req: Request, res: Response) => {
  if (!req.file) {
    return res.status(400).json({ success: false, error: 'No audio file uploaded' });
  }

  const fileUrl = `/uploads/${req.file.filename}`;

  // Analyze audio specs (simulated high resolution WAV analysis)
  const spec = {
    fileName: req.file.originalname,
    fileSizeBytes: req.file.size,
    format: req.file.originalname.toUpperCase().endsWith('.FLAC') ? 'FLAC' : 'WAV',
    sampleRateHz: 48000,
    bitDepth: 24,
    channels: 'Stereo',
    durationSeconds: 204, // 3:24
    peakLufs: -14.1,
    url: fileUrl,
  };

  res.json({
    success: true,
    fileUrl,
    spec,
    message: 'Audio master verified and validated (24-bit / 48kHz WAV, -14.1 LUFS).',
  });
});

// 10. File upload: Artwork
app.post('/api/upload/artwork', upload.single('artwork'), (req: Request, res: Response) => {
  if (!req.file) {
    return res.status(400).json({ success: false, error: 'No artwork file uploaded' });
  }

  const fileUrl = `/uploads/${req.file.filename}`;

  res.json({
    success: true,
    fileUrl,
    spec: {
      width: 3000,
      height: 3000,
      colorSpace: 'RGB',
      format: req.file.mimetype.includes('png') ? 'PNG' : 'JPEG',
      sizeBytes: req.file.size,
      hasTextRestrictionsPassed: true,
    },
    message: 'Artwork verified: 3000x3000px sRGB standard passed.',
  });
});

// 11. Royalties & Payouts
app.get('/api/royalties/ledger', (_req: Request, res: Response) => {
  res.json({
    success: true,
    balance: 5124.60,
    currency: 'USD',
    artistKeepPercentage: 100,
  });
});

app.post('/api/royalties/payout', (req: Request, res: Response) => {
  const db = getDb();
  const { amount, method, accountReference } = req.body;

  const newPayout = {
    id: `payout-${Date.now().toString(36)}`,
    amount: parseFloat(amount) || 5124.60,
    currency: 'USD',
    method: method || 'Stripe Direct',
    requestedAt: new Date().toISOString(),
    status: 'PROCESSED',
    accountReference: accountReference || 'acct_1NZX****8892',
  };

  db.payouts.unshift(newPayout);
  saveDb(db);

  res.json({
    success: true,
    message: `Payout of $${newPayout.amount.toFixed(2)} USD successfully initiated via ${newPayout.method}.`,
    payout: newPayout,
  });
});

// Start listening
app.listen(PORT, () => {
  console.log(`====================================================`);
  console.log(`🎧 SONVÉRA Distribution Backend Server running`);
  console.log(`📡 URL: http://127.0.0.1:${PORT}`);
  console.log(`🚀 Provider: SonveraDemoProvider (DDEX ERN 4.3 Active)`);
  console.log(`====================================================`);
});
